/*******************************************************************************
 *
 * Copyright (c) 2004-2008 by Vivante Corp.  All rights reserved.
 *
 * The material in this file is confidential and contains trade secrets of
 * Vivante Corporation.  This is proprietary information owned by Vivante
 * Corporation.  No part of this work may be disclosed, reproduced, copied,
 * transmitted, or used in any way for any purpose, without the express
 * written permission of Vivante Corporation.
 *
 ******************************************************************************/

/*******************************************************************************
 *
 * This file is automatically generated on Mon Apr 13 01:22:32 2009
 *
 * Any changes made to this file are lost at the next compile run!
 * So better make sure you update the source .r files instead!
 *
 ******************************************************************************/

#include "AQCommon.h"
#include "AQPixelEngineReg.h"
#include "AQMemoryReg.h"
#include "AQSetupReg.h"
#include "AQCommand.h"
#include "AQDrawingEngine.h"
#include "AQPrimitiveAssembly.h"
#include "AQTexture.h"
#include "AQDma.h"
#include "AQShader.h"
#include "AQPowerManagementReg.h"
#include "AQRasterReg.h"
#include "AQResolveReg.h"
#include "AQHostInterface.h"
#include "gcregDisplay.h"
