/*******************************************************************************
 *
 * Copyright (c) 2004,2005,2006 by GiQuila Corp. All rights reserved.
 *
 * The material in this file is confidential and contains trade secrets of
 * GiQuila Corporation. This is proprietary information owned by GiQuila
 * Corporation. No part of this work may be disclosed, reproduced, copied,
 * transmitted, or used in any way for any purpose, without the express
 * written permission of GiQuila Corporation.
 *
 ******************************************************************************/

/*******************************************************************************
 *
 * This file is automatically generated on Fri May 30 00:08:57 2008
 *
 * Any changes made to this file are lost at the next compile run!
 * So better make sure you update the source .r files instead!
 *
 ******************************************************************************/

////////////////////////////////////////////////////////////////////////////////
//                          ~~~~~~~~~~~~~~~~~~~~~~~~                          //
//                          Module DisplayController                          //
//                          ~~~~~~~~~~~~~~~~~~~~~~~~                          //
////////////////////////////////////////////////////////////////////////////////

// Register AQDisplayConfig (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayConfigRegAddrs                                           0x0A00
#define AQ_DISPLAY_CONFIG_Address                                        0x02800
#define AQ_DISPLAY_CONFIG_MSB                                                 15
#define AQ_DISPLAY_CONFIG_LSB                                                  1
#define AQ_DISPLAY_CONFIG_Count                                                2
#define AQ_DISPLAY_CONFIG_FieldMask                                   0xC0111117
#define AQ_DISPLAY_CONFIG_ReadMask                                    0xC0101117
#define AQ_DISPLAY_CONFIG_WriteMask                                   0x40111117
#define AQ_DISPLAY_CONFIG_ResetValue                                  0x00000000

#define AQ_DISPLAY_CONFIG_FLIP_IN_PROGRESS                                 31:31
#define AQ_DISPLAY_CONFIG_FLIP_IN_PROGRESS_End                                31
#define AQ_DISPLAY_CONFIG_FLIP_IN_PROGRESS_Start                              31
#define   AQ_DISPLAY_CONFIG_FLIP_IN_PROGRESS_NO                              0x0
#define   AQ_DISPLAY_CONFIG_FLIP_IN_PROGRESS_YES                             0x1

#define AQ_DISPLAY_CONFIG_UNDERFLOW                                        30:30
#define AQ_DISPLAY_CONFIG_UNDERFLOW_End                                       30
#define AQ_DISPLAY_CONFIG_UNDERFLOW_Start                                     30
#define   AQ_DISPLAY_CONFIG_UNDERFLOW_NO                                     0x0
#define   AQ_DISPLAY_CONFIG_UNDERFLOW_YES                                    0x1

#define AQ_DISPLAY_CONFIG_GAMMA                                            20:20
#define AQ_DISPLAY_CONFIG_GAMMA_End                                           20
#define AQ_DISPLAY_CONFIG_GAMMA_Start                                         20
#define   AQ_DISPLAY_CONFIG_GAMMA_DISABLE                                    0x0
#define   AQ_DISPLAY_CONFIG_GAMMA_ENABLE                                     0x1

#define AQ_DISPLAY_CONFIG_RESET                                            16:16
#define AQ_DISPLAY_CONFIG_RESET_End                                           16
#define AQ_DISPLAY_CONFIG_RESET_Start                                         16
#define   AQ_DISPLAY_CONFIG_RESET_RESET                                      0x1

#define AQ_DISPLAY_CONFIG_OUTPUT                                           12:12
#define AQ_DISPLAY_CONFIG_OUTPUT_End                                          12
#define AQ_DISPLAY_CONFIG_OUTPUT_Start                                        12
#define   AQ_DISPLAY_CONFIG_OUTPUT_DISABLED                                  0x0
#define   AQ_DISPLAY_CONFIG_OUTPUT_ENABLED                                   0x1

#define AQ_DISPLAY_CONFIG_ROTATION                                           8:8
#define AQ_DISPLAY_CONFIG_ROTATION_End                                         8
#define AQ_DISPLAY_CONFIG_ROTATION_Start                                       8
#define   AQ_DISPLAY_CONFIG_ROTATION_NORMAL                                  0x0
#define   AQ_DISPLAY_CONFIG_ROTATION_ROTATED                                 0x1

#define AQ_DISPLAY_CONFIG_STEREO                                             4:4
#define AQ_DISPLAY_CONFIG_STEREO_End                                           4
#define AQ_DISPLAY_CONFIG_STEREO_Start                                         4
#define   AQ_DISPLAY_CONFIG_STEREO_DISABLED                                  0x0
#define   AQ_DISPLAY_CONFIG_STEREO_ENABLED                                   0x1

#define AQ_DISPLAY_CONFIG_FORMAT                                             2:0
#define AQ_DISPLAY_CONFIG_FORMAT_End                                           2
#define AQ_DISPLAY_CONFIG_FORMAT_Start                                         0
#define   AQ_DISPLAY_CONFIG_FORMAT_NONE                                      0x0
#define   AQ_DISPLAY_CONFIG_FORMAT_R4G4B4                                    0x1
#define   AQ_DISPLAY_CONFIG_FORMAT_R5G5B5                                    0x2
#define   AQ_DISPLAY_CONFIG_FORMAT_R5G6B5                                    0x3
#define   AQ_DISPLAY_CONFIG_FORMAT_R8G8B8                                    0x4
#define   AQ_DISPLAY_CONFIG_FORMAT_R10G10B10                                 0x5

// Register AQDisplayAddressLeft (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayAddressLeftRegAddrs                                      0x0A02
#define AQ_DISPLAY_ADDRESS_LEFT_Address                                  0x02808
#define AQ_DISPLAY_ADDRESS_LEFT_MSB                                           15
#define AQ_DISPLAY_ADDRESS_LEFT_LSB                                            1
#define AQ_DISPLAY_ADDRESS_LEFT_Count                                          2
#define AQ_DISPLAY_ADDRESS_LEFT_FieldMask                             0xFFFFFFFF
#define AQ_DISPLAY_ADDRESS_LEFT_ReadMask                              0xFFFFFFFC
#define AQ_DISPLAY_ADDRESS_LEFT_WriteMask                             0xFFFFFFFC
#define AQ_DISPLAY_ADDRESS_LEFT_ResetValue                            0x00000000

#define AQ_DISPLAY_ADDRESS_LEFT_TYPE                                       31:31
#define AQ_DISPLAY_ADDRESS_LEFT_TYPE_End                                      31
#define AQ_DISPLAY_ADDRESS_LEFT_TYPE_Start                                    31
#define   AQ_DISPLAY_ADDRESS_LEFT_TYPE_SYSTEM                                0x0
#define   AQ_DISPLAY_ADDRESS_LEFT_TYPE_VIRTUAL_SYSTEM                        0x1

#define AQ_DISPLAY_ADDRESS_LEFT_ADDRESS                                     30:0
#define AQ_DISPLAY_ADDRESS_LEFT_ADDRESS_End                                   30
#define AQ_DISPLAY_ADDRESS_LEFT_ADDRESS_Start                                  0

// Register AQDisplayAddressRight (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayAddressRightRegAddrs                                     0x0A04
#define AQ_DISPLAY_ADDRESS_RIGHT_Address                                 0x02810
#define AQ_DISPLAY_ADDRESS_RIGHT_MSB                                          15
#define AQ_DISPLAY_ADDRESS_RIGHT_LSB                                           1
#define AQ_DISPLAY_ADDRESS_RIGHT_Count                                         2
#define AQ_DISPLAY_ADDRESS_RIGHT_FieldMask                            0xFFFFFFFF
#define AQ_DISPLAY_ADDRESS_RIGHT_ReadMask                             0xFFFFFFFC
#define AQ_DISPLAY_ADDRESS_RIGHT_WriteMask                            0xFFFFFFFC
#define AQ_DISPLAY_ADDRESS_RIGHT_ResetValue                           0x00000000

#define AQ_DISPLAY_ADDRESS_RIGHT_TYPE                                      31:31
#define AQ_DISPLAY_ADDRESS_RIGHT_TYPE_End                                     31
#define AQ_DISPLAY_ADDRESS_RIGHT_TYPE_Start                                   31
#define   AQ_DISPLAY_ADDRESS_RIGHT_TYPE_SYSTEM                               0x0
#define   AQ_DISPLAY_ADDRESS_RIGHT_TYPE_VIRTUAL_SYSTEM                       0x1

#define AQ_DISPLAY_ADDRESS_RIGHT_ADDRESS                                    30:0
#define AQ_DISPLAY_ADDRESS_RIGHT_ADDRESS_End                                  30
#define AQ_DISPLAY_ADDRESS_RIGHT_ADDRESS_Start                                 0

// Register AQDisplayStride (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayStrideRegAddrs                                           0x0A06
#define AQ_DISPLAY_STRIDE_Address                                        0x02818
#define AQ_DISPLAY_STRIDE_MSB                                                 15
#define AQ_DISPLAY_STRIDE_LSB                                                  1
#define AQ_DISPLAY_STRIDE_Count                                                2
#define AQ_DISPLAY_STRIDE_FieldMask                                   0x0003FFFF
#define AQ_DISPLAY_STRIDE_ReadMask                                    0x0003FFFC
#define AQ_DISPLAY_STRIDE_WriteMask                                   0x0003FFFC
#define AQ_DISPLAY_STRIDE_ResetValue                                  0x00000000

#define AQ_DISPLAY_STRIDE_STRIDE                                            17:0
#define AQ_DISPLAY_STRIDE_STRIDE_End                                          17
#define AQ_DISPLAY_STRIDE_STRIDE_Start                                         0

// Register AQDisplayOrigin (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayOriginRegAddrs                                           0x0A08
#define AQ_DISPLAY_ORIGIN_Address                                        0x02820
#define AQ_DISPLAY_ORIGIN_MSB                                                 15
#define AQ_DISPLAY_ORIGIN_LSB                                                  1
#define AQ_DISPLAY_ORIGIN_Count                                                2
#define AQ_DISPLAY_ORIGIN_FieldMask                                   0x7FFF7FFF
#define AQ_DISPLAY_ORIGIN_ReadMask                                    0x7FFF7FFF
#define AQ_DISPLAY_ORIGIN_WriteMask                                   0x7FFF7FFF
#define AQ_DISPLAY_ORIGIN_ResetValue                                  0x00000000

#define AQ_DISPLAY_ORIGIN_Y                                                30:16
#define AQ_DISPLAY_ORIGIN_Y_End                                               30
#define AQ_DISPLAY_ORIGIN_Y_Start                                             16

#define AQ_DISPLAY_ORIGIN_X                                                 14:0
#define AQ_DISPLAY_ORIGIN_X_End                                               14
#define AQ_DISPLAY_ORIGIN_X_Start                                              0

// Register AQDisplayScale (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayScaleRegAddrs                                            0x0A0A
#define AQ_DISPLAY_SCALE_Address                                         0x02828
#define AQ_DISPLAY_SCALE_MSB                                                  15
#define AQ_DISPLAY_SCALE_LSB                                                   1
#define AQ_DISPLAY_SCALE_Count                                                 2
#define AQ_DISPLAY_SCALE_FieldMask                                    0x03FF03FF
#define AQ_DISPLAY_SCALE_ReadMask                                     0x03FF03FF
#define AQ_DISPLAY_SCALE_WriteMask                                    0x03FF03FF
#define AQ_DISPLAY_SCALE_ResetValue                                   0x00000000

#define AQ_DISPLAY_SCALE_VERTICAL                                          25:24
#define AQ_DISPLAY_SCALE_VERTICAL_End                                         25
#define AQ_DISPLAY_SCALE_VERTICAL_Start                                       24
#define   AQ_DISPLAY_SCALE_VERTICAL_DISABLED                                 0x0
#define   AQ_DISPLAY_SCALE_VERTICAL_REPLICATED                               0x1
#define   AQ_DISPLAY_SCALE_VERTICAL_INTERPOLATED                             0x2

#define AQ_DISPLAY_SCALE_VERTICAL_FACTOR                                   23:16
#define AQ_DISPLAY_SCALE_VERTICAL_FACTOR_End                                  23
#define AQ_DISPLAY_SCALE_VERTICAL_FACTOR_Start                                16

#define AQ_DISPLAY_SCALE_HORIZONTAL                                          9:8
#define AQ_DISPLAY_SCALE_HORIZONTAL_End                                        9
#define AQ_DISPLAY_SCALE_HORIZONTAL_Start                                      8
#define   AQ_DISPLAY_SCALE_HORIZONTAL_DISABLED                               0x0
#define   AQ_DISPLAY_SCALE_HORIZONTAL_REPLICATED                             0x1
#define   AQ_DISPLAY_SCALE_HORIZONTAL_INTERPOLATED                           0x2

#define AQ_DISPLAY_SCALE_HORIZONTAL_FACTOR                                   7:0
#define AQ_DISPLAY_SCALE_HORIZONTAL_FACTOR_End                                 7
#define AQ_DISPLAY_SCALE_HORIZONTAL_FACTOR_Start                               0

// Register AQDisplayModeSize (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayModeSizeRegAddrs                                         0x0A0C
#define AQ_DISPLAY_MODE_SIZE_Address                                     0x02830
#define AQ_DISPLAY_MODE_SIZE_MSB                                              15
#define AQ_DISPLAY_MODE_SIZE_LSB                                               1
#define AQ_DISPLAY_MODE_SIZE_Count                                             2
#define AQ_DISPLAY_MODE_SIZE_FieldMask                                0x07FF07FF
#define AQ_DISPLAY_MODE_SIZE_ReadMask                                 0x07FF07FF
#define AQ_DISPLAY_MODE_SIZE_WriteMask                                0x07FF07FF
#define AQ_DISPLAY_MODE_SIZE_ResetValue                               0x00000000

#define AQ_DISPLAY_MODE_SIZE_HEIGHT                                        26:16
#define AQ_DISPLAY_MODE_SIZE_HEIGHT_End                                       26
#define AQ_DISPLAY_MODE_SIZE_HEIGHT_Start                                     16

#define AQ_DISPLAY_MODE_SIZE_WIDTH                                          10:0
#define AQ_DISPLAY_MODE_SIZE_WIDTH_End                                        10
#define AQ_DISPLAY_MODE_SIZE_WIDTH_Start                                       0

// Register AQDisplayDitherConfig (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayDitherConfigRegAddrs                                     0x0A0E
#define AQ_DISPLAY_DITHER_CONFIG_Address                                 0x02838
#define AQ_DISPLAY_DITHER_CONFIG_MSB                                          15
#define AQ_DISPLAY_DITHER_CONFIG_LSB                                           1
#define AQ_DISPLAY_DITHER_CONFIG_Count                                         2
#define AQ_DISPLAY_DITHER_CONFIG_FieldMask                            0x8FFF0FFF
#define AQ_DISPLAY_DITHER_CONFIG_ReadMask                             0x8FFF0FFF
#define AQ_DISPLAY_DITHER_CONFIG_WriteMask                            0x8FFF0FFF
#define AQ_DISPLAY_DITHER_CONFIG_ResetValue                           0x00000000

#define AQ_DISPLAY_DITHER_CONFIG_ENABLE                                    31:31
#define AQ_DISPLAY_DITHER_CONFIG_ENABLE_End                                   31
#define AQ_DISPLAY_DITHER_CONFIG_ENABLE_Start                                 31
#define   AQ_DISPLAY_DITHER_CONFIG_ENABLE_DISABLED                           0x0
#define   AQ_DISPLAY_DITHER_CONFIG_ENABLE_ENABLED                            0x1

#define AQ_DISPLAY_DITHER_CONFIG_RED_SIZE                                  27:24
#define AQ_DISPLAY_DITHER_CONFIG_RED_SIZE_End                                 27
#define AQ_DISPLAY_DITHER_CONFIG_RED_SIZE_Start                               24

#define AQ_DISPLAY_DITHER_CONFIG_GREEN_SIZE                                23:20
#define AQ_DISPLAY_DITHER_CONFIG_GREEN_SIZE_End                               23
#define AQ_DISPLAY_DITHER_CONFIG_GREEN_SIZE_Start                             20

#define AQ_DISPLAY_DITHER_CONFIG_BLUE_SIZE                                 19:16
#define AQ_DISPLAY_DITHER_CONFIG_BLUE_SIZE_End                                19
#define AQ_DISPLAY_DITHER_CONFIG_BLUE_SIZE_Start                              16

#define AQ_DISPLAY_DITHER_CONFIG_RED_START                                  11:8
#define AQ_DISPLAY_DITHER_CONFIG_RED_START_End                                11
#define AQ_DISPLAY_DITHER_CONFIG_RED_START_Start                               8

#define AQ_DISPLAY_DITHER_CONFIG_GREEN_START                                 7:4
#define AQ_DISPLAY_DITHER_CONFIG_GREEN_START_End                               7
#define AQ_DISPLAY_DITHER_CONFIG_GREEN_START_Start                             4

#define AQ_DISPLAY_DITHER_CONFIG_BLUE_START                                  3:0
#define AQ_DISPLAY_DITHER_CONFIG_BLUE_START_End                                3
#define AQ_DISPLAY_DITHER_CONFIG_BLUE_START_Start                              0

// Register AQDisplayDitherTable (4 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayDitherTableRegAddrs                                      0x0A10
#define AQ_DISPLAY_DITHER_TABLE_Address                                  0x02840
#define AQ_DISPLAY_DITHER_TABLE_MSB                                           15
#define AQ_DISPLAY_DITHER_TABLE_LSB                                            2
#define AQ_DISPLAY_DITHER_TABLE_Count                                          4
#define AQ_DISPLAY_DITHER_TABLE_FieldMask                             0xFFFFFFFF
#define AQ_DISPLAY_DITHER_TABLE_ReadMask                              0xFFFFFFFF
#define AQ_DISPLAY_DITHER_TABLE_WriteMask                             0xFFFFFFFF
#define AQ_DISPLAY_DITHER_TABLE_ResetValue                            0x00000000

#define AQ_DISPLAY_DITHER_TABLE_Y0_X0                                        3:0
#define AQ_DISPLAY_DITHER_TABLE_Y0_X0_End                                      3
#define AQ_DISPLAY_DITHER_TABLE_Y0_X0_Start                                    0

#define AQ_DISPLAY_DITHER_TABLE_Y0_X1                                        7:4
#define AQ_DISPLAY_DITHER_TABLE_Y0_X1_End                                      7
#define AQ_DISPLAY_DITHER_TABLE_Y0_X1_Start                                    4

#define AQ_DISPLAY_DITHER_TABLE_Y0_X2                                       11:8
#define AQ_DISPLAY_DITHER_TABLE_Y0_X2_End                                     11
#define AQ_DISPLAY_DITHER_TABLE_Y0_X2_Start                                    8

#define AQ_DISPLAY_DITHER_TABLE_Y0_X3                                      15:12
#define AQ_DISPLAY_DITHER_TABLE_Y0_X3_End                                     15
#define AQ_DISPLAY_DITHER_TABLE_Y0_X3_Start                                   12

#define AQ_DISPLAY_DITHER_TABLE_Y1_X0                                      19:16
#define AQ_DISPLAY_DITHER_TABLE_Y1_X0_End                                     19
#define AQ_DISPLAY_DITHER_TABLE_Y1_X0_Start                                   16

#define AQ_DISPLAY_DITHER_TABLE_Y1_X1                                      23:20
#define AQ_DISPLAY_DITHER_TABLE_Y1_X1_End                                     23
#define AQ_DISPLAY_DITHER_TABLE_Y1_X1_Start                                   20

#define AQ_DISPLAY_DITHER_TABLE_Y1_X2                                      27:24
#define AQ_DISPLAY_DITHER_TABLE_Y1_X2_End                                     27
#define AQ_DISPLAY_DITHER_TABLE_Y1_X2_Start                                   24

#define AQ_DISPLAY_DITHER_TABLE_Y1_X3                                      31:28
#define AQ_DISPLAY_DITHER_TABLE_Y1_X3_End                                     31
#define AQ_DISPLAY_DITHER_TABLE_Y1_X3_Start                                   28

// Register AQDisplayPanel (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayPanelRegAddrs                                            0x0A14
#define AQ_DISPLAY_PANEL_Address                                         0x02850
#define AQ_DISPLAY_PANEL_MSB                                                  15
#define AQ_DISPLAY_PANEL_LSB                                                   1
#define AQ_DISPLAY_PANEL_Count                                                 2
#define AQ_DISPLAY_PANEL_FieldMask                                    0x99BB8B91
#define AQ_DISPLAY_PANEL_ReadMask                                     0x99BB8B91
#define AQ_DISPLAY_PANEL_WriteMask                                    0x99BB8B91
#define AQ_DISPLAY_PANEL_ResetValue                                   0x00000000

#define AQ_DISPLAY_PANEL_POWER_POLARITY                                    31:31
#define AQ_DISPLAY_PANEL_POWER_POLARITY_End                                   31
#define AQ_DISPLAY_PANEL_POWER_POLARITY_Start                                 31
#define   AQ_DISPLAY_PANEL_POWER_POLARITY_POSITIVE                           0x0
#define   AQ_DISPLAY_PANEL_POWER_POLARITY_NEGATIVE                           0x1

#define AQ_DISPLAY_PANEL_POWER                                             28:28
#define AQ_DISPLAY_PANEL_POWER_End                                            28
#define AQ_DISPLAY_PANEL_POWER_Start                                          28
#define   AQ_DISPLAY_PANEL_POWER_DISABLED                                    0x0
#define   AQ_DISPLAY_PANEL_POWER_ENABLED                                     0x1

#define AQ_DISPLAY_PANEL_BACKLIGHT_POLARITY                                27:27
#define AQ_DISPLAY_PANEL_BACKLIGHT_POLARITY_End                               27
#define AQ_DISPLAY_PANEL_BACKLIGHT_POLARITY_Start                             27
#define   AQ_DISPLAY_PANEL_BACKLIGHT_POLARITY_POSITIVE                       0x0
#define   AQ_DISPLAY_PANEL_BACKLIGHT_POLARITY_NEGATIVE                       0x1

#define AQ_DISPLAY_PANEL_BACKLIGHT                                         24:24
#define AQ_DISPLAY_PANEL_BACKLIGHT_End                                        24
#define AQ_DISPLAY_PANEL_BACKLIGHT_Start                                      24
#define   AQ_DISPLAY_PANEL_BACKLIGHT_DISABLED                                0x0
#define   AQ_DISPLAY_PANEL_BACKLIGHT_ENABLED                                 0x1

#define AQ_DISPLAY_PANEL_CLOCK_POLARITY                                    23:23
#define AQ_DISPLAY_PANEL_CLOCK_POLARITY_End                                   23
#define AQ_DISPLAY_PANEL_CLOCK_POLARITY_Start                                 23
#define   AQ_DISPLAY_PANEL_CLOCK_POLARITY_POSITIVE                           0x0
#define   AQ_DISPLAY_PANEL_CLOCK_POLARITY_NEGATIVE                           0x1

#define AQ_DISPLAY_PANEL_CLOCK_INACTIVE                                    21:21
#define AQ_DISPLAY_PANEL_CLOCK_INACTIVE_End                                   21
#define AQ_DISPLAY_PANEL_CLOCK_INACTIVE_Start                                 21
#define   AQ_DISPLAY_PANEL_CLOCK_INACTIVE_NORMAL                             0x0
#define   AQ_DISPLAY_PANEL_CLOCK_INACTIVE_FORCED_LOW                         0x1

#define AQ_DISPLAY_PANEL_CLOCK                                             20:20
#define AQ_DISPLAY_PANEL_CLOCK_End                                            20
#define AQ_DISPLAY_PANEL_CLOCK_Start                                          20
#define   AQ_DISPLAY_PANEL_CLOCK_DISABLED                                    0x0
#define   AQ_DISPLAY_PANEL_CLOCK_ENABLED                                     0x1

#define AQ_DISPLAY_PANEL_DE_POLARITY                                       19:19
#define AQ_DISPLAY_PANEL_DE_POLARITY_End                                      19
#define AQ_DISPLAY_PANEL_DE_POLARITY_Start                                    19
#define   AQ_DISPLAY_PANEL_DE_POLARITY_POSITIVE                              0x0
#define   AQ_DISPLAY_PANEL_DE_POLARITY_NEGATIVE                              0x1

#define AQ_DISPLAY_PANEL_DE_INACTIVE                                       17:17
#define AQ_DISPLAY_PANEL_DE_INACTIVE_End                                      17
#define AQ_DISPLAY_PANEL_DE_INACTIVE_Start                                    17
#define   AQ_DISPLAY_PANEL_DE_INACTIVE_NORMAL                                0x0
#define   AQ_DISPLAY_PANEL_DE_INACTIVE_FORCED_LOW                            0x1

#define AQ_DISPLAY_PANEL_DE                                                16:16
#define AQ_DISPLAY_PANEL_DE_End                                               16
#define AQ_DISPLAY_PANEL_DE_Start                                             16
#define   AQ_DISPLAY_PANEL_DE_DISABLED                                       0x0
#define   AQ_DISPLAY_PANEL_DE_ENABLED                                        0x1

#define AQ_DISPLAY_PANEL_DATA_POLARITY                                     15:15
#define AQ_DISPLAY_PANEL_DATA_POLARITY_End                                    15
#define AQ_DISPLAY_PANEL_DATA_POLARITY_Start                                  15
#define   AQ_DISPLAY_PANEL_DATA_POLARITY_POSITIVE                            0x0
#define   AQ_DISPLAY_PANEL_DATA_POLARITY_NEGATIVE                            0x1

#define AQ_DISPLAY_PANEL_HSYNC_POLARITY                                    11:11
#define AQ_DISPLAY_PANEL_HSYNC_POLARITY_End                                   11
#define AQ_DISPLAY_PANEL_HSYNC_POLARITY_Start                                 11
#define   AQ_DISPLAY_PANEL_HSYNC_POLARITY_POSITIVE                           0x0
#define   AQ_DISPLAY_PANEL_HSYNC_POLARITY_NEGATIVE                           0x1

#define AQ_DISPLAY_PANEL_HSYNC_INACTIVE                                      9:9
#define AQ_DISPLAY_PANEL_HSYNC_INACTIVE_End                                    9
#define AQ_DISPLAY_PANEL_HSYNC_INACTIVE_Start                                  9
#define   AQ_DISPLAY_PANEL_HSYNC_INACTIVE_NORMAL                             0x0
#define   AQ_DISPLAY_PANEL_HSYNC_INACTIVE_FORCED_LOW                         0x1

#define AQ_DISPLAY_PANEL_HSYNC                                               8:8
#define AQ_DISPLAY_PANEL_HSYNC_End                                             8
#define AQ_DISPLAY_PANEL_HSYNC_Start                                           8
#define   AQ_DISPLAY_PANEL_HSYNC_DISABLED                                    0x0
#define   AQ_DISPLAY_PANEL_HSYNC_ENABLED                                     0x1

#define AQ_DISPLAY_PANEL_VSYNC_POLARITY                                      7:7
#define AQ_DISPLAY_PANEL_VSYNC_POLARITY_End                                    7
#define AQ_DISPLAY_PANEL_VSYNC_POLARITY_Start                                  7
#define   AQ_DISPLAY_PANEL_VSYNC_POLARITY_POSITIVE                           0x0
#define   AQ_DISPLAY_PANEL_VSYNC_POLARITY_NEGATIVE                           0x1

#define AQ_DISPLAY_PANEL_VSYNC                                               4:4
#define AQ_DISPLAY_PANEL_VSYNC_End                                             4
#define AQ_DISPLAY_PANEL_VSYNC_Start                                           4
#define   AQ_DISPLAY_PANEL_VSYNC_DISABLED                                    0x0
#define   AQ_DISPLAY_PANEL_VSYNC_ENABLED                                     0x1

#define AQ_DISPLAY_PANEL_SEQUENCING                                          0:0
#define AQ_DISPLAY_PANEL_SEQUENCING_End                                        0
#define AQ_DISPLAY_PANEL_SEQUENCING_Start                                      0
#define   AQ_DISPLAY_PANEL_SEQUENCING_HARDWARE                               0x0
#define   AQ_DISPLAY_PANEL_SEQUENCING_SOFTWARE                               0x1

// Register AQDisplayPanelTiming (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayPanelTimingRegAddrs                                      0x0A16
#define AQ_DISPLAY_PANEL_TIMING_Address                                  0x02858
#define AQ_DISPLAY_PANEL_TIMING_MSB                                           15
#define AQ_DISPLAY_PANEL_TIMING_LSB                                            1
#define AQ_DISPLAY_PANEL_TIMING_Count                                          2
#define AQ_DISPLAY_PANEL_TIMING_FieldMask                             0xFFFFFFFF
#define AQ_DISPLAY_PANEL_TIMING_ReadMask                              0xFFFFFFFF
#define AQ_DISPLAY_PANEL_TIMING_WriteMask                             0xFFFFFFFF
#define AQ_DISPLAY_PANEL_TIMING_ResetValue                            0x00000000

#define AQ_DISPLAY_PANEL_TIMING_POWER_DISABLE                              31:28
#define AQ_DISPLAY_PANEL_TIMING_POWER_DISABLE_End                             31
#define AQ_DISPLAY_PANEL_TIMING_POWER_DISABLE_Start                           28

#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_DISABLE                          27:24
#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_DISABLE_End                         27
#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_DISABLE_Start                       24

#define AQ_DISPLAY_PANEL_TIMING_CLOCK_DISABLE                              23:20
#define AQ_DISPLAY_PANEL_TIMING_CLOCK_DISABLE_End                             23
#define AQ_DISPLAY_PANEL_TIMING_CLOCK_DISABLE_Start                           20

#define AQ_DISPLAY_PANEL_TIMING_DATA_DISABLE                               19:16
#define AQ_DISPLAY_PANEL_TIMING_DATA_DISABLE_End                              19
#define AQ_DISPLAY_PANEL_TIMING_DATA_DISABLE_Start                            16

#define AQ_DISPLAY_PANEL_TIMING_POWER_ENABLE                               15:12
#define AQ_DISPLAY_PANEL_TIMING_POWER_ENABLE_End                              15
#define AQ_DISPLAY_PANEL_TIMING_POWER_ENABLE_Start                            12

#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_ENABLE                            11:8
#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_ENABLE_End                          11
#define AQ_DISPLAY_PANEL_TIMING_BACKLIGHT_ENABLE_Start                         8

#define AQ_DISPLAY_PANEL_TIMING_CLOCK_ENABLE                                 7:4
#define AQ_DISPLAY_PANEL_TIMING_CLOCK_ENABLE_End                               7
#define AQ_DISPLAY_PANEL_TIMING_CLOCK_ENABLE_Start                             4

#define AQ_DISPLAY_PANEL_TIMING_DATA_ENABLE                                  3:0
#define AQ_DISPLAY_PANEL_TIMING_DATA_ENABLE_End                                3
#define AQ_DISPLAY_PANEL_TIMING_DATA_ENABLE_Start                              0

// Register AQDisplayFifoControl (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayFifoControlRegAddrs                                      0x0A18
#define AQ_DISPLAY_FIFO_CONTROL_Address                                  0x02860
#define AQ_DISPLAY_FIFO_CONTROL_MSB                                           15
#define AQ_DISPLAY_FIFO_CONTROL_LSB                                            1
#define AQ_DISPLAY_FIFO_CONTROL_Count                                          2
#define AQ_DISPLAY_FIFO_CONTROL_FieldMask                             0x00001F1F
#define AQ_DISPLAY_FIFO_CONTROL_ReadMask                              0x00001F1F
#define AQ_DISPLAY_FIFO_CONTROL_WriteMask                             0x00001F1F
#define AQ_DISPLAY_FIFO_CONTROL_ResetValue                            0x00001810

#define AQ_DISPLAY_FIFO_CONTROL_LOW_WMARK                                    4:0
#define AQ_DISPLAY_FIFO_CONTROL_LOW_WMARK_End                                  4
#define AQ_DISPLAY_FIFO_CONTROL_LOW_WMARK_Start                                0

#define AQ_DISPLAY_FIFO_CONTROL_HIGH_WMARK                                  12:8
#define AQ_DISPLAY_FIFO_CONTROL_HIGH_WMARK_End                                12
#define AQ_DISPLAY_FIFO_CONTROL_HIGH_WMARK_Start                               8

// Register AQDisplayHDisplay (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayHDisplayRegAddrs                                         0x0A1A
#define AQ_DISPLAY_HDISPLAY_Address                                      0x02868
#define AQ_DISPLAY_HDISPLAY_MSB                                               15
#define AQ_DISPLAY_HDISPLAY_LSB                                                1
#define AQ_DISPLAY_HDISPLAY_Count                                              2
#define AQ_DISPLAY_HDISPLAY_FieldMask                                 0x07FF07FF
#define AQ_DISPLAY_HDISPLAY_ReadMask                                  0x07FF07FF
#define AQ_DISPLAY_HDISPLAY_WriteMask                                 0x07FF07FF
#define AQ_DISPLAY_HDISPLAY_ResetValue                                0x00000000

#define AQ_DISPLAY_HDISPLAY_TOTAL                                          26:16
#define AQ_DISPLAY_HDISPLAY_TOTAL_End                                         26
#define AQ_DISPLAY_HDISPLAY_TOTAL_Start                                       16

#define AQ_DISPLAY_HDISPLAY_DISPLAY_END                                     10:0
#define AQ_DISPLAY_HDISPLAY_DISPLAY_END_End                                   10
#define AQ_DISPLAY_HDISPLAY_DISPLAY_END_Start                                  0

// Register AQDisplayHSync (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayHSyncRegAddrs                                            0x0A1C
#define AQ_DISPLAY_HSYNC_Address                                         0x02870
#define AQ_DISPLAY_HSYNC_MSB                                                  15
#define AQ_DISPLAY_HSYNC_LSB                                                   1
#define AQ_DISPLAY_HSYNC_Count                                                 2
#define AQ_DISPLAY_HSYNC_FieldMask                                    0x07FF07FF
#define AQ_DISPLAY_HSYNC_ReadMask                                     0x07FF07FF
#define AQ_DISPLAY_HSYNC_WriteMask                                    0x07FF07FF
#define AQ_DISPLAY_HSYNC_ResetValue                                   0x00000000

#define AQ_DISPLAY_HSYNC_END                                               26:16
#define AQ_DISPLAY_HSYNC_END_End                                              26
#define AQ_DISPLAY_HSYNC_END_Start                                            16

#define AQ_DISPLAY_HSYNC_START                                              10:0
#define AQ_DISPLAY_HSYNC_START_End                                            10
#define AQ_DISPLAY_HSYNC_START_Start                                           0

// Register AQDisplayVDisplay (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayVDisplayRegAddrs                                         0x0A1E
#define AQ_DISPLAY_VDISPLAY_Address                                      0x02878
#define AQ_DISPLAY_VDISPLAY_MSB                                               15
#define AQ_DISPLAY_VDISPLAY_LSB                                                1
#define AQ_DISPLAY_VDISPLAY_Count                                              2
#define AQ_DISPLAY_VDISPLAY_FieldMask                                 0x07FF07FF
#define AQ_DISPLAY_VDISPLAY_ReadMask                                  0x07FF07FF
#define AQ_DISPLAY_VDISPLAY_WriteMask                                 0x07FF07FF
#define AQ_DISPLAY_VDISPLAY_ResetValue                                0x00000000

#define AQ_DISPLAY_VDISPLAY_TOTAL                                          26:16
#define AQ_DISPLAY_VDISPLAY_TOTAL_End                                         26
#define AQ_DISPLAY_VDISPLAY_TOTAL_Start                                       16

#define AQ_DISPLAY_VDISPLAY_DISPLAY_END                                     10:0
#define AQ_DISPLAY_VDISPLAY_DISPLAY_END_End                                   10
#define AQ_DISPLAY_VDISPLAY_DISPLAY_END_Start                                  0

// Register AQDisplayVSync (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayVSyncRegAddrs                                            0x0A20
#define AQ_DISPLAY_VSYNC_Address                                         0x02880
#define AQ_DISPLAY_VSYNC_MSB                                                  15
#define AQ_DISPLAY_VSYNC_LSB                                                   1
#define AQ_DISPLAY_VSYNC_Count                                                 2
#define AQ_DISPLAY_VSYNC_FieldMask                                    0x07FF07FF
#define AQ_DISPLAY_VSYNC_ReadMask                                     0x07FF07FF
#define AQ_DISPLAY_VSYNC_WriteMask                                    0x07FF07FF
#define AQ_DISPLAY_VSYNC_ResetValue                                   0x00000000

#define AQ_DISPLAY_VSYNC_END                                               26:16
#define AQ_DISPLAY_VSYNC_END_End                                              26
#define AQ_DISPLAY_VSYNC_END_Start                                            16

#define AQ_DISPLAY_VSYNC_START                                              10:0
#define AQ_DISPLAY_VSYNC_START_End                                            10
#define AQ_DISPLAY_VSYNC_START_Start                                           0

// Register AQDisplayCurrentLocation (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayCurrentLocationRegAddrs                                  0x0A22
#define AQ_DISPLAY_CURRENT_LOCATION_Address                              0x02888
#define AQ_DISPLAY_CURRENT_LOCATION_MSB                                       15
#define AQ_DISPLAY_CURRENT_LOCATION_LSB                                        1
#define AQ_DISPLAY_CURRENT_LOCATION_Count                                      2
#define AQ_DISPLAY_CURRENT_LOCATION_FieldMask                         0x7FFF7FFF
#define AQ_DISPLAY_CURRENT_LOCATION_ReadMask                          0x7FFF7FFF
#define AQ_DISPLAY_CURRENT_LOCATION_WriteMask                         0x7FFF7FFF
#define AQ_DISPLAY_CURRENT_LOCATION_ResetValue                        0x00000000

#define AQ_DISPLAY_CURRENT_LOCATION_Y                                      30:16
#define AQ_DISPLAY_CURRENT_LOCATION_Y_End                                     30
#define AQ_DISPLAY_CURRENT_LOCATION_Y_Start                                   16

#define AQ_DISPLAY_CURRENT_LOCATION_X                                       14:0
#define AQ_DISPLAY_CURRENT_LOCATION_X_End                                     14
#define AQ_DISPLAY_CURRENT_LOCATION_X_Start                                    0

// Register AQCursorConfig.
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQCursorConfigRegAddrs                                            0x0A24
#define AQ_CURSOR_CONFIG_Address                                         0x02890
#define AQ_CURSOR_CONFIG_MSB                                                  15
#define AQ_CURSOR_CONFIG_LSB                                                   0
#define AQ_CURSOR_CONFIG_Count                                                 1
#define AQ_CURSOR_CONFIG_FieldMask                                    0x801F1F13
#define AQ_CURSOR_CONFIG_ReadMask                                     0x801F1F13
#define AQ_CURSOR_CONFIG_WriteMask                                    0x001F1F13
#define AQ_CURSOR_CONFIG_ResetValue                                   0x00000000

#define AQ_CURSOR_CONFIG_FLIP_IN_PROGRESS                                  31:31
#define AQ_CURSOR_CONFIG_FLIP_IN_PROGRESS_End                                 31
#define AQ_CURSOR_CONFIG_FLIP_IN_PROGRESS_Start                               31
#define   AQ_CURSOR_CONFIG_FLIP_IN_PROGRESS_NO                               0x0
#define   AQ_CURSOR_CONFIG_FLIP_IN_PROGRESS_YES                              0x1

#define AQ_CURSOR_CONFIG_HOT_SPOT_X                                        20:16
#define AQ_CURSOR_CONFIG_HOT_SPOT_X_End                                       20
#define AQ_CURSOR_CONFIG_HOT_SPOT_X_Start                                     16

#define AQ_CURSOR_CONFIG_HOT_SPOT_Y                                         12:8
#define AQ_CURSOR_CONFIG_HOT_SPOT_Y_End                                       12
#define AQ_CURSOR_CONFIG_HOT_SPOT_Y_Start                                      8

#define AQ_CURSOR_CONFIG_DISPLAY                                             4:4
#define AQ_CURSOR_CONFIG_DISPLAY_End                                           4
#define AQ_CURSOR_CONFIG_DISPLAY_Start                                         4
#define   AQ_CURSOR_CONFIG_DISPLAY_DISPLAY0                                  0x0
#define   AQ_CURSOR_CONFIG_DISPLAY_DISPLAY1                                  0x1

#define AQ_CURSOR_CONFIG_FORMAT                                              1:0
#define AQ_CURSOR_CONFIG_FORMAT_End                                            1
#define AQ_CURSOR_CONFIG_FORMAT_Start                                          0
#define   AQ_CURSOR_CONFIG_FORMAT_DISABLED                                   0x0
#define   AQ_CURSOR_CONFIG_FORMAT_MASKED                                     0x1
#define   AQ_CURSOR_CONFIG_FORMAT_M32IRGB4                                   0x2
#define   AQ_CURSOR_CONFIG_FORMAT_A4R4G4B4                                   0x3

// Register AQCursorAddress.
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQCursorAddressRegAddrs                                           0x0A25
#define AQ_CURSOR_ADDRESS_Address                                        0x02894
#define AQ_CURSOR_ADDRESS_MSB                                                 15
#define AQ_CURSOR_ADDRESS_LSB                                                  0
#define AQ_CURSOR_ADDRESS_Count                                                1
#define AQ_CURSOR_ADDRESS_FieldMask                                   0xFFFFFFFF
#define AQ_CURSOR_ADDRESS_ReadMask                                    0xFFFFFFFC
#define AQ_CURSOR_ADDRESS_WriteMask                                   0xFFFFFFFC
#define AQ_CURSOR_ADDRESS_ResetValue                                  0x00000000

#define AQ_CURSOR_ADDRESS_TYPE                                             31:31
#define AQ_CURSOR_ADDRESS_TYPE_End                                            31
#define AQ_CURSOR_ADDRESS_TYPE_Start                                          31
#define   AQ_CURSOR_ADDRESS_TYPE_SYSTEM                                      0x0
#define   AQ_CURSOR_ADDRESS_TYPE_VIRTUAL_SYSTEM                              0x1

#define AQ_CURSOR_ADDRESS_ADDRESS                                           30:0
#define AQ_CURSOR_ADDRESS_ADDRESS_End                                         30
#define AQ_CURSOR_ADDRESS_ADDRESS_Start                                        0

// Register AQCursorLocation.
// ~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQCursorLocationRegAddrs                                          0x0A26
#define AQ_CURSOR_LOCATION_Address                                       0x02898
#define AQ_CURSOR_LOCATION_MSB                                                15
#define AQ_CURSOR_LOCATION_LSB                                                 0
#define AQ_CURSOR_LOCATION_Count                                               1
#define AQ_CURSOR_LOCATION_FieldMask                                  0x7FFF7FFF
#define AQ_CURSOR_LOCATION_ReadMask                                   0x7FFF7FFF
#define AQ_CURSOR_LOCATION_WriteMask                                  0x7FFF7FFF
#define AQ_CURSOR_LOCATION_ResetValue                                 0x00000000

#define AQ_CURSOR_LOCATION_Y                                               30:16
#define AQ_CURSOR_LOCATION_Y_End                                              30
#define AQ_CURSOR_LOCATION_Y_Start                                            16

#define AQ_CURSOR_LOCATION_X                                                14:0
#define AQ_CURSOR_LOCATION_X_End                                              14
#define AQ_CURSOR_LOCATION_X_Start                                             0

// Register AQCursorLookup (16 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~
#define AQCursorLookupRegAddrs                                            0x0A30
#define AQ_CURSOR_LOOKUP_Address                                         0x028C0
#define AQ_CURSOR_LOOKUP_MSB                                                  15
#define AQ_CURSOR_LOOKUP_LSB                                                   4
#define AQ_CURSOR_LOOKUP_Count                                                16
#define AQ_CURSOR_LOOKUP_FieldMask                                    0x3FFFFFFF
#define AQ_CURSOR_LOOKUP_ReadMask                                     0x3FFFFFFF
#define AQ_CURSOR_LOOKUP_WriteMask                                    0x3FFFFFFF
#define AQ_CURSOR_LOOKUP_ResetValue                                   0x00000000

#define AQ_CURSOR_LOOKUP_RED                                               29:20
#define AQ_CURSOR_LOOKUP_RED_End                                              29
#define AQ_CURSOR_LOOKUP_RED_Start                                            20

#define AQ_CURSOR_LOOKUP_GREEN                                             19:10
#define AQ_CURSOR_LOOKUP_GREEN_End                                            19
#define AQ_CURSOR_LOOKUP_GREEN_Start                                          10

#define AQ_CURSOR_LOOKUP_BLUE                                                9:0
#define AQ_CURSOR_LOOKUP_BLUE_End                                              9
#define AQ_CURSOR_LOOKUP_BLUE_Start                                            0

// Register AQDCBistControl.
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDCBistControlRegAddrs                                           0x0A27
#define AQDC_BIST_CONTROL_Address                                        0x0289C
#define AQDC_BIST_CONTROL_MSB                                                 15
#define AQDC_BIST_CONTROL_LSB                                                  0
#define AQDC_BIST_CONTROL_Count                                                1
#define AQDC_BIST_CONTROL_FieldMask                                   0x00000003
#define AQDC_BIST_CONTROL_ReadMask                                    0x00000003
#define AQDC_BIST_CONTROL_WriteMask                                   0x00000003
#define AQDC_BIST_CONTROL_ResetValue                                  0x00000000

#define AQDC_BIST_CONTROL_RESET                                              0:0
#define AQDC_BIST_CONTROL_RESET_End                                            0
#define AQDC_BIST_CONTROL_RESET_Start                                          0
#define   AQDC_BIST_CONTROL_RESET_NOT_RESET                                  0x0
#define   AQDC_BIST_CONTROL_RESET_RESET                                      0x1

#define AQDC_BIST_CONTROL_MODE                                               1:1
#define AQDC_BIST_CONTROL_MODE_End                                             1
#define AQDC_BIST_CONTROL_MODE_Start                                           1
#define   AQDC_BIST_CONTROL_MODE_NOT_BIST_MODE                               0x0
#define   AQDC_BIST_CONTROL_MODE_BIST_MODE                                   0x1

// Register AQDCBistStatus0.
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDCBistStatus0RegAddrs                                           0x0A28
#define AQDC_BIST_STATUS0_Address                                        0x028A0
#define AQDC_BIST_STATUS0_MSB                                                 15
#define AQDC_BIST_STATUS0_LSB                                                  0
#define AQDC_BIST_STATUS0_Count                                                1
#define AQDC_BIST_STATUS0_FieldMask                                   0x00000001
#define AQDC_BIST_STATUS0_ReadMask                                    0x00000001
#define AQDC_BIST_STATUS0_WriteMask                                   0x00000001
#define AQDC_BIST_STATUS0_ResetValue                                  0x00000000

#define AQDC_BIST_STATUS0_DONE                                               0:0
#define AQDC_BIST_STATUS0_DONE_End                                             0
#define AQDC_BIST_STATUS0_DONE_Start                                           0
#define   AQDC_BIST_STATUS0_DONE_NOT_DONE                                    0x0
#define   AQDC_BIST_STATUS0_DONE_DONE                                        0x1

// Register AQDCBistStatus1.
// ~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDCBistStatus1RegAddrs                                           0x0A29
#define AQDC_BIST_STATUS1_Address                                        0x028A4
#define AQDC_BIST_STATUS1_MSB                                                 15
#define AQDC_BIST_STATUS1_LSB                                                  0
#define AQDC_BIST_STATUS1_Count                                                1
#define AQDC_BIST_STATUS1_FieldMask                                   0x0000007F
#define AQDC_BIST_STATUS1_ReadMask                                    0x0000007F
#define AQDC_BIST_STATUS1_WriteMask                                   0x0000007F
#define AQDC_BIST_STATUS1_ResetValue                                  0x00000000

// 7 rams in DC
#define AQDC_BIST_STATUS1_BM_ERROR                                           6:0
#define AQDC_BIST_STATUS1_BM_ERROR_End                                         6
#define AQDC_BIST_STATUS1_BM_ERROR_Start                                       0

// Register AQDisplayGammaIndex (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayGammaIndexRegAddrs                                       0x0A2A
#define AQ_DISPLAY_GAMMA_INDEX_Address                                   0x028A8
#define AQ_DISPLAY_GAMMA_INDEX_MSB                                            15
#define AQ_DISPLAY_GAMMA_INDEX_LSB                                             1
#define AQ_DISPLAY_GAMMA_INDEX_Count                                           2
#define AQ_DISPLAY_GAMMA_INDEX_FieldMask                              0x000000FF
#define AQ_DISPLAY_GAMMA_INDEX_ReadMask                               0x000000FF
#define AQ_DISPLAY_GAMMA_INDEX_WriteMask                              0x000000FF
#define AQ_DISPLAY_GAMMA_INDEX_ResetValue                             0x00000000

#define AQ_DISPLAY_GAMMA_INDEX_INDEX                                         7:0
#define AQ_DISPLAY_GAMMA_INDEX_INDEX_End                                       7
#define AQ_DISPLAY_GAMMA_INDEX_INDEX_Start                                     0

// Register AQDisplayGammaData (2 in total).
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~
#define AQDisplayGammaDataRegAddrs                                        0x0A2C
#define AQ_DISPLAY_GAMMA_DATA_Address                                    0x028B0
#define AQ_DISPLAY_GAMMA_DATA_MSB                                             15
#define AQ_DISPLAY_GAMMA_DATA_LSB                                              1
#define AQ_DISPLAY_GAMMA_DATA_Count                                            2
#define AQ_DISPLAY_GAMMA_DATA_FieldMask                               0x3FFFFFFF
#define AQ_DISPLAY_GAMMA_DATA_ReadMask                                0x3FFFFFFF
#define AQ_DISPLAY_GAMMA_DATA_WriteMask                               0x3FFFFFFF
#define AQ_DISPLAY_GAMMA_DATA_ResetValue                              0x00000000

#define AQ_DISPLAY_GAMMA_DATA_RED                                            9:0
#define AQ_DISPLAY_GAMMA_DATA_RED_End                                          9
#define AQ_DISPLAY_GAMMA_DATA_RED_Start                                        0

#define AQ_DISPLAY_GAMMA_DATA_GREEN                                        19:10
#define AQ_DISPLAY_GAMMA_DATA_GREEN_End                                       19
#define AQ_DISPLAY_GAMMA_DATA_GREEN_Start                                     10

#define AQ_DISPLAY_GAMMA_DATA_BLUE                                         29:20
#define AQ_DISPLAY_GAMMA_DATA_BLUE_End                                        29
#define AQ_DISPLAY_GAMMA_DATA_BLUE_Start                                      20

