/*******************************************************************************
 *
 * Copyright (c) 2004-2008 by Vivante Corp.  All rights reserved.
 *
 * The material in this file is confidential and contains trade secrets of
 * Vivante Corporation.  This is proprietary information owned by Vivante
 * Corporation.  No part of this work may be disclosed, reproduced, copied,
 * transmitted, or used in any way for any purpose, without the express
 * written permission of Vivante Corporation.
 *
 ******************************************************************************/

/*******************************************************************************
 *
 * This file is automatically generated on Mon Apr 13 01:22:32 2009
 *
 * Any changes made to this file are lost at the next compile run!
 * So better make sure you update the source .r files instead!
 *
 ******************************************************************************/

////////////////////////////////////////////////////////////////////////////////
//                             ~~~~~~~~~~~~~~~~~~                             //
//                             Module SetupEngine                             //
//                             ~~~~~~~~~~~~~~~~~~                             //
////////////////////////////////////////////////////////////////////////////////

// Register AQSetupClipLeft.
// ~~~~~~~~~~~~~~~~~~~~~~~~

// Left coordinate of the clipping window

#define AQSetupClipLeftRegAddrs                                           0x0300
#define AQ_SETUP_CLIP_LEFT_Address                                       0x00C00
#define AQ_SETUP_CLIP_LEFT_MSB                                                15
#define AQ_SETUP_CLIP_LEFT_LSB                                                 0
#define AQ_SETUP_CLIP_LEFT_Count                                               1
#define AQ_SETUP_CLIP_LEFT_FieldMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_ReadMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_WriteMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_ResetValue                                 0x00000000

// The left coordinate of the clipping window in float.
#define AQ_SETUP_CLIP_LEFT_CLIP                                             31:0
#define AQ_SETUP_CLIP_LEFT_CLIP_End                                           31
#define AQ_SETUP_CLIP_LEFT_CLIP_Start                                          0

// Register AQSetupClipTop.
// ~~~~~~~~~~~~~~~~~~~~~~~

// Top coordinate of the clipping window

#define AQSetupClipTopRegAddrs                                            0x0301
#define AQ_SETUP_CLIP_TOP_Address                                        0x00C04
#define AQ_SETUP_CLIP_TOP_MSB                                                 15
#define AQ_SETUP_CLIP_TOP_LSB                                                  0
#define AQ_SETUP_CLIP_TOP_Count                                                1
#define AQ_SETUP_CLIP_TOP_FieldMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_ReadMask                                    0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_WriteMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_ResetValue                                  0x00000000

// The top coordinate of the clipping window in float.
#define AQ_SETUP_CLIP_TOP_CLIP                                              31:0
#define AQ_SETUP_CLIP_TOP_CLIP_End                                            31
#define AQ_SETUP_CLIP_TOP_CLIP_Start                                           0

// Register AQSetupClipRight.
// ~~~~~~~~~~~~~~~~~~~~~~~~~

// Right coordinate of the clipping window

#define AQSetupClipRightRegAddrs                                          0x0302
#define AQ_SETUP_CLIP_RIGHT_Address                                      0x00C08
#define AQ_SETUP_CLIP_RIGHT_MSB                                               15
#define AQ_SETUP_CLIP_RIGHT_LSB                                                0
#define AQ_SETUP_CLIP_RIGHT_Count                                              1
#define AQ_SETUP_CLIP_RIGHT_FieldMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_ReadMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_WriteMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_ResetValue                                0x45000000

// The right coordinate of the clipping window in float.
// This coordinate is exclusive, meaning the width is
// computed as Right - Left.
#define AQ_SETUP_CLIP_RIGHT_CLIP                                            31:0
#define AQ_SETUP_CLIP_RIGHT_CLIP_End                                          31
#define AQ_SETUP_CLIP_RIGHT_CLIP_Start                                         0

// Register AQSetupClipBottom.
// ~~~~~~~~~~~~~~~~~~~~~~~~~~

// Bottom coordinate of the clipping window

#define AQSetupClipBottomRegAddrs                                         0x0303
#define AQ_SETUP_CLIP_BOTTOM_Address                                     0x00C0C
#define AQ_SETUP_CLIP_BOTTOM_MSB                                              15
#define AQ_SETUP_CLIP_BOTTOM_LSB                                               0
#define AQ_SETUP_CLIP_BOTTOM_Count                                             1
#define AQ_SETUP_CLIP_BOTTOM_FieldMask                                0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_ReadMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_WriteMask                                0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_ResetValue                               0x45000000

// The bottom coordinate of the clipping window in float.
// This coordinate is exclusive, meaning the height is
// computed as Bottom - Top.
#define AQ_SETUP_CLIP_BOTTOM_CLIP                                           31:0
#define AQ_SETUP_CLIP_BOTTOM_CLIP_End                                         31
#define AQ_SETUP_CLIP_BOTTOM_CLIP_Start                                        0

// Register AQSetupSlopeScaledDepthBias.
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

// depthFactor

#define AQSetupSlopeScaledDepthBiasRegAddrs                               0x0304
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_Address                         0x00C10
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_MSB                                  15
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_LSB                                   0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_Count                                 1
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_FieldMask                    0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_ReadMask                     0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_WriteMask                    0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_ResetValue                   0x00000000

// The multiplicative part depthFactor in the formula:
// zInit += m * depthFactor + depthBias, in float.
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS                               31:0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS_End                             31
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS_Start                            0

// Register AQSetupDepthBias.
// ~~~~~~~~~~~~~~~~~~~~~~~~~

// depthBias

#define AQSetupDepthBiasRegAddrs                                          0x0305
#define AQ_SETUP_DEPTH_BIAS_Address                                      0x00C14
#define AQ_SETUP_DEPTH_BIAS_MSB                                               15
#define AQ_SETUP_DEPTH_BIAS_LSB                                                0
#define AQ_SETUP_DEPTH_BIAS_Count                                              1
#define AQ_SETUP_DEPTH_BIAS_FieldMask                                 0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_ReadMask                                  0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_WriteMask                                 0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_ResetValue                                0x00000000

// The additive part depthBias in the the formula:
// zInit += m*depthFactor + depthBiasm in float.
#define AQ_SETUP_DEPTH_BIAS_BIAS                                            31:0
#define AQ_SETUP_DEPTH_BIAS_BIAS_End                                          31
#define AQ_SETUP_DEPTH_BIAS_BIAS_Start                                         0

// Register AQSetupConfig.
// ~~~~~~~~~~~~~~~~~~~~~~

// Render last pixel in lines

#define AQSetupConfigRegAddrs                                             0x0306
#define AQ_SETUP_CONFIG_Address                                          0x00C18
#define AQ_SETUP_CONFIG_MSB                                                   15
#define AQ_SETUP_CONFIG_LSB                                                    0
#define AQ_SETUP_CONFIG_Count                                                  1
#define AQ_SETUP_CONFIG_FieldMask                                     0x00000001
#define AQ_SETUP_CONFIG_ReadMask                                      0x00000001
#define AQ_SETUP_CONFIG_WriteMask                                     0x00000001
#define AQ_SETUP_CONFIG_ResetValue                                    0x00000000

// Enable rendering of the last pixel in a line.
#define AQ_SETUP_CONFIG_LAST_PIXEL                                           0:0
#define AQ_SETUP_CONFIG_LAST_PIXEL_End                                         0
#define AQ_SETUP_CONFIG_LAST_PIXEL_Start                                       0
#define   AQ_SETUP_CONFIG_LAST_PIXEL_DISABLE                                 0x0
#define   AQ_SETUP_CONFIG_LAST_PIXEL_ENABLE                                  0x1

